### ISSUE TITLE
UnboundLocalError: local variable 'start_cmd' referenced before assignment

### ISSUE THREAD

**Issue by hackedbellini** [xbianonpi/xbian#727]
On rpi2 using stable + staging repositories, I found this on my kodi.log:

```
23:09:42 T:1784673296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'start_cmd' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/usr/local/share/kodi/addons/script.service.xbian.upstart-bridge/service.py", line 205, in <module>
                                                service = UpstartBridge()
                                              File "/usr/local/share/kodi/addons/script.service.xbian.upstart-bridge/service.py", line 25, in __init__
                                                self._notify_xbmc_loaded()
                                              File "/usr/local/share/kodi/addons/script.service.xbian.upstart-bridge/service.py", line 79, in _notify_xbmc_loaded
                                                log('dummy action. xbmc-loaded would be called. : %s' % ' '.join(start_cmd), xbmc.LOGDEBUG)
                                            UnboundLocalError: local variable 'start_cmd' referenced before assignment
                                            -->End of Python script error report<--
```

**Comment by CurlyMoo** [comment]
To all xbian-config-xbmc error reports. The package is not being maintained at the moment. Until someone can pick it up again, we can't do anything with the errors.
